#!/usr/bin/env python3

# Liberias necesarias
import rospy
from std_msgs.msg import Bool
from pyfirmata import Arduino, util
import pyfirmata


# variables
led= 13      # led de confirmación para recepción de datos
boton= 7     # pin para boton
val= False   # Inicializa como falso

arduino = Arduino("/dev/ttyACM3")  # Puerto de arduino

it = util.Iterator(arduino)
it.start()
arduino.digital[boton].mode = pyfirmata.INPUT

if __name__ == '__main__':

	# Inicializa nodo
	rospy.init_node('boton_node', anonymous=True)
	pub_boton = rospy.Publisher('bandera_boton', Bool , queue_size=10)
	rate = rospy.Rate(10)	

	while not rospy.is_shutdown():

		val = arduino.digital[boton].read()  # Lee el estado del botón 
		arduino.digital[led].write(val)      # Prende led si se presiona el boton
		rospy.loginfo(val)
		pub_boton.publish(val)
		
		rate.sleep()